
'use strict';
const slides=JSON.parse(document.getElementById('slide-data').textContent);
const qaIndex=30,deeperIndex=31,sourceIndex=37;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let index=0,revealed=0,showAll=true,popup=null,presenter=!location.hash.startsWith('#audience'),linked=!presenter&&!!window.opener,localMode=!linked;
let running=false,elapsedMs=0,slideMs=0,targetMin=45,lastTick=Date.now(),lastSync=0;
const audienceKey=new URLSearchParams(location.hash.split('?')[1]||'').get('session');
const sessionStorageKey='workshop-presenter:'+location.pathname;
function presenterSession(){try{let key=sessionStorage.getItem(sessionStorageKey);if(!key){key=crypto.randomUUID();sessionStorage.setItem(sessionStorageKey,key)}return key}catch(e){if(!window.name.startsWith('workshop-owner:'))window.name='workshop-owner:'+crypto.randomUUID();return window.name.slice(15)}}
const sessionKey=presenter?presenterSession():audienceKey;
const bootId=crypto.randomUUID();
let audienceBoot=null;
function ready(){if(linked&&sessionKey)window.opener?.postMessage({type:'deck-ready',sessionKey},'*')}

function content(i){const s=slides[i];return '<section class="slide" aria-label="'+esc(s.title)+'"><p class="eyebrow">'+s.section+'</p>'+(i===0?'':'<h2>'+s.title+'</h2>')+s.html+'<div class="slide-disclaimer"><em>Views expressed are my own and do not necessarily reflect those of my employer.</em></div></section>'}
function count(i=index){return(slides[i].html.match(/class="[^"]*reveal/g)||[]).length}
function nextSlide(){return index===qaIndex?qaIndex:Math.min(index+1,slides.length-1)}
function fit(){let v=$('viewport');$('stage').style.transform='scale('+Math.min(v.clientWidth/1280,v.clientHeight/720)+')';document.querySelectorAll('.preview-box').forEach(b=>{const scale=Math.min(b.clientWidth/1280,b.clientHeight/720);b.firstElementChild.style.transform=(b.id==='currentPreview'?'translate(-50%,-50%) ':'')+'scale('+scale+')'})}
function markReveals(root,amount){root.querySelectorAll('.reveal').forEach((e,n)=>{let hide=!showAll&&n>=amount;e.classList.toggle('pending',hide);e.setAttribute('aria-hidden',hide?'true':'false')})}
function render(){const s=slides[index];$('stage').innerHTML=content(index);markReveals($('stage'),revealed);$('jump').value=index;$('stateText').textContent=(index+1)+' / '+slides.length+' · '+(s.kind==='main'?'Main talk':s.kind==='deep'?'Go Deeper':'Sources');$('progress').style.width=((index+1)/slides.length*100)+'%';$('announcement').textContent='Slide '+(index+1)+'. '+s.title+'.';$('inlineNotes').textContent=s.notes;
$('currentPreview').firstElementChild.innerHTML=content(index);markReveals($('currentPreview'),revealed);const n=nextSlide();$('nextPreview').firstElementChild.innerHTML=content(n);$('nextLabel').textContent=index===qaIndex?'End of main talk. Optional material is available from the toolbar.':index===slides.length-1?'End of sources. Press End to return to Q&A.':(n+1)+'. '+slides[n].title;$('notes').textContent=s.notes;$('prev').disabled=index===0&&revealed===0;$('next').disabled=(index===qaIndex||index===slides.length-1)&&(showAll||revealed===count());
history.replaceState(null,'','#'+(presenter?'presenter':'audience')+'-slide-'+(index+1)+'-'+revealed+(!presenter&&sessionKey?'?session='+encodeURIComponent(sessionKey):''));document.title=s.title+' · '+(presenter?'Presenter':'AI-Assisted Development');fit();sync()}
function tick(){let now=Date.now(),d=now-lastTick;lastTick=now;if(running&&(!linked||localMode)){elapsedMs+=d;slideMs+=d}drawTime()}
function fmt(ms){let t=Math.floor(Math.abs(ms)/1000);return(ms<0?'-':'')+String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0')}
function drawTime(){$('elapsed').textContent=fmt(elapsedMs);$('slideTime').textContent=fmt(slideMs);$('remaining').textContent=fmt(targetMin*60000-elapsedMs);$('remaining').style.color=elapsedMs>targetMin*60000?'var(--warn)':'var(--accent)';$('startTimer').textContent=running?'Pause timer':'Start timer';if(document.activeElement!==$('target'))$('target').value=targetMin;if(presenter)$('linkState').textContent=popup&&!popup.closed?'Presentation window open. Slides are synchronized.':'Presenter panel ready. Launch the presentation view for your audience.'}
function state(){return{type:'deck-state',sessionKey,bootId,index,revealed,showAll,running,elapsedMs,slideMs,targetMin}}
function sync(){if(popup&&!popup.closed)popup.postMessage(state(),'*')}
function command(action,value){if(linked&&!localMode){window.opener.postMessage({type:'deck-command',sessionKey,action,value},'*');return}tick();if(action==='next'){if(!showAll&&revealed<count())revealed++;else if(nextSlide()!==index){index=nextSlide();revealed=0;slideMs=0}}if(action==='prev'){if(!showAll&&revealed>0)revealed--;else if(index>0){index--;revealed=count();slideMs=0}}if(action==='jump'){index=Math.min(slides.length-1,Math.max(0,Number(value)||0));revealed=0;slideMs=0}if(action==='timer')running=!running;if(action==='reset'){running=false;elapsedMs=0;slideMs=0}if(action==='target')targetMin=Math.max(1,Math.min(240,Number(value)||45));render();drawTime()}
window.addEventListener('message',e=>{if(!sessionKey||e.data?.sessionKey!==sessionKey)return;if(presenter&&e.data.type==='deck-ready'&&e.source&&e.source!==window){if(!popup||popup.closed)popup=e.source;if(e.source===popup){sync();return}}if(e.source===popup&&e.data?.type==='deck-ready'){sync();return}if(e.source===popup&&e.data?.type==='deck-command'){if(['next','prev','jump','timer','reset','target'].includes(e.data.action))command(e.data.action,e.data.value);return}if(linked&&!localMode&&e.source===window.opener&&e.data?.type==='deck-state'){const d=e.data;const mustReload=audienceBoot!==null&&audienceBoot!==d.bootId;audienceBoot=d.bootId;let changed=index!==d.index||revealed!==d.revealed||showAll!==d.showAll;index=d.index;revealed=d.revealed;showAll=true;running=d.running;elapsedMs=d.elapsedMs;slideMs=d.slideMs;targetMin=d.targetMin;lastSync=Date.now();if(changed||mustReload)render();drawTime();if(mustReload)location.reload()}});
function consoleMode(on){presenter=on;document.body.classList.toggle('presenter',on);if(on)document.body.classList.remove('reading');fit();render()}
function notice(s){$('notice').textContent=s;setTimeout(()=>$('notice').textContent='',7000)}
function openAudience(){if(!presenter)return;if(popup&&!popup.closed){popup.focus();sync();return}popup=window.open(location.href.split('#')[0]+'#audience-slide-'+(index+1)+'-'+revealed+'?session='+encodeURIComponent(sessionKey),'workshop-audience-'+sessionKey,'width=1280,height=800');if(!popup)notice('Presentation window blocked. Allow pop-ups, then choose Launch presentation view again.');else notice('Presentation view requested. Keep this presenter panel on your private display.');}

function openDialog(id){const d=$(id);if(!d.open)d.showModal()}
function readMode(){document.body.classList.toggle('reading');fit()}
function fullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>notice('Full screen unavailable. Use your browser’s full-screen control.'));else document.exitFullscreen?.()}
$('printChecklist').innerHTML=$('checklist').innerHTML.replace(/ id="[^"]*"/g,'');
slides.forEach((s,i)=>{let opt=document.createElement('option');opt.value=i;opt.textContent=String(i+1).padStart(2,'0')+' · '+(s.kind==='deep'?'[Deeper] ':s.kind==='sources'?'[Sources] ':'')+s.title;$('jump').appendChild(opt)});
$('reading').innerHTML='<h1>AI-Assisted Development</h1><p>Code Quality, Security &amp; Human Oversight<br>Patrick Pierre-Louis · Software Engineer · Bank of America</p>'+slides.map((s,i)=>'<article><p class="eyebrow">'+s.section+'</p><h2>'+(i+1)+'. '+s.title+'</h2>'+s.html+'<p class="reading-disclaimer"><em>Views expressed are my own and do not necessarily reflect those of my employer.</em></p><details><summary>Presenter notes</summary><p>'+esc(s.notes).replace(/\n/g,'<br>')+'</p></details></article>').join('');
$('prev').onclick=()=>command('prev');$('next').onclick=()=>command('next');$('jump').onchange=e=>{document.body.classList.remove('reading');command('jump',e.target.value)};$('read').onclick=readMode;$('check').onclick=()=>openDialog('checklist');$('help').onclick=()=>openDialog('helpDialog');$('deeper').onclick=()=>{document.body.classList.remove('reading');command('jump',deeperIndex)};$('sources').onclick=()=>{document.body.classList.remove('reading');command('jump',sourceIndex)};$('returnQA').onclick=()=>command('jump',qaIndex);$('startTimer').onclick=()=>command('timer');$('resetTimer').onclick=()=>command('reset');$('target').onchange=e=>command('target',e.target.value);$('launchAudience').onclick=openAudience;

document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('motion').onclick=()=>{document.body.classList.toggle('no-motion');$('motion').textContent=document.body.classList.contains('no-motion')?'Enable motion':'Disable motion'};
$('printCheck').onclick=()=>{document.body.classList.add('print-check');window.print()};$('printDeck').onclick=()=>{$('helpDialog').close();document.body.classList.remove('print-check');window.print()};window.addEventListener('afterprint',()=>document.body.classList.remove('print-check'));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('blackout');$('inlineNotes').classList.remove('open');return}if(document.querySelector('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable)return;if((e.key===' '||e.key==='Enter')&&e.target.closest('button,a,summary'))return;let k=e.key.toLowerCase();const actions={'arrowright':()=>command('next'),'pagedown':()=>command('next'),' ':()=>command('next'),'arrowleft':()=>command('prev'),'pageup':()=>command('prev'),'home':()=>command('jump',0),'end':()=>command('jump',qaIndex),'p':openAudience,'n':()=>$('inlineNotes').classList.toggle('open'),'f':fullscreen,'b':()=>document.body.classList.toggle('blackout'),'c':()=>openDialog('checklist'),'g':()=>{document.body.classList.remove('reading');command('jump',deeperIndex)},'s':()=>{document.body.classList.remove('reading');command('jump',sourceIndex)},'r':readMode,'?':()=>openDialog('helpDialog')};if(actions[k]){e.preventDefault();actions[k]()}});
let match=location.hash.match(/^#(?:(?:presenter|audience)-)?slide-(\d+)-(\d+)(?:\?.*)?$/);if(match){index=Math.max(0,Math.min(slides.length-1,Number(match[1])-1));revealed=Math.min(count(),Number(match[2]))}if(presenter)document.body.classList.add('presenter');ready();render();drawTime();window.addEventListener('resize',fit);new ResizeObserver(fit).observe($('currentPreview'));setInterval(()=>{tick();if(!linked||localMode)sync();else ready()},500);
